spring:
  application:
    name: ai-search-gpt

ai-search:
  elasticsearch-url: ${AI_SEARCH_ES_URL:http://localhost:9200}
  username: ${AI_SEARCH_ES_USERNAME:elastic}
  password: ${AI_SEARCH_ES_PASSWORD:mHSD62AxK3c25Pr2nQGIXtDc}
  index-name: ${AI_SEARCH_ES_INDEX:food-products-v1}
  embedding-model-url: ${AI_SEARCH_EMBED_MODEL:djl://ai.djl.huggingface.pytorch/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2}
