spring:
  application:
    name: ai-search-gpt

ai-search:
  elasticsearch-url: ${AI_SEARCH_ES_URL:http://localhost:9200}
  username: ${AI_SEARCH_ES_USERNAME:elastic}
  password: ${AI_SEARCH_ES_PASSWORD:password}
  index-name: ${AI_SEARCH_ES_INDEX:food-products-v1-test}
  # embedding-model-path 우선 적용하며, 없으면 model-url 사용함
  embedding-model-path: ${AI_SEARCH_EMBED_MODEL_PATH:classpath:/model/multilingual-e5-small-ko-v2}
#  embedding-model-url: ${AI_SEARCH_EMBED_MODEL:djl://ai.djl.huggingface.pytorch/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2}
  min-score-threshold: ${AI_SEARCH_MIN_SCORE:0.74}
  num-candidates-multiplier: ${AI_SEARCH_NUM_CANDIDATES_MULTIPLIER:5}
  num-candidates-min: ${AI_SEARCH_NUM_CANDIDATES_MIN:50}
  k8s:
    auto-port-forward: ${AI_SEARCH_AUTO_PORT_FORWARD:true}
    namespace: ${AI_SEARCH_K8S_NAMESPACE:ai-search}
    service-name: ${AI_SEARCH_K8S_SERVICE:}
    secret-name: ${AI_SEARCH_K8S_SECRET:ai-search-es-es-elastic-user}
    local-port: ${AI_SEARCH_K8S_LOCAL_PORT:9200}
    remote-port: ${AI_SEARCH_K8S_REMOTE_PORT:9200}
